[package]
name = "trenitalia_cli"
version = "0.1.0"
authors = ["Michael Chelli <michaelchelli00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
drs_primitives = { git = "https://github.com/eutampieri/drs-primitives" }
trenitalia = {git="https://github.com/eutampieri/trenitalia.git"}
